jobs:
  main:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./run/test

name: Workflow

on:
  schedule:
    - cron: "10 1/3 * * *"
